[package]
name = "savefile"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
binrw.workspace = true
derive_more.workspace = true

[dev-dependencies]
rstest.workspace = true
rstest_reuse.workspace = true
