name: Bump Version

on:
  workflow_dispatch:
    inputs:
      level:
        description: "Cargo-Release bump option (patch, minor, major)"
        required: true
        default: "minor"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0

      - run: cargo install cargo-release
      - run: cargo release ${{ inputs.level }} --no-publish --no-push --execute

      - run: |
          git push
          git push --tags
