name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  clippy-and-test:
    name: Clippy and Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0

      - run: cargo clippy --workspace
      - run: cargo test --workspace --all-features
