name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  TOOLCHAIN_VERSION: 1.86.0

jobs:
  clippy-and-test:
    name: Clippy and Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.TOOLCHAIN_VERSION }}
          components: clippy

      - run: cargo clippy --workspace
      - run: cargo test --workspace --all-features
